name: Docker Compose Workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12-dind
        options: --privileged
        ports:
          - 2375:2375

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: üìÅ Init
      run: |
        # Set permissions for checkout.
        sudo chown -R 1000:1000 $(pwd)

        # Create performance testing results directory.
        sudo mkdir -p vendor
        sudo mkdir -p core
        sudo mkdir -p modules/contrib
        sudo chmod 777 vendor
        sudo chmod 777 core
        sudo chmod 777 modules/contrib

    - name: üì¶ Setup
      run: |
        docker compose up -d --wait
        docker compose exec -T --user wodby php /bin/sh -c "cd /var/www/html/ && composer install --prefer-dist --no-progress"
        docker compose exec -T --user wodby php /bin/sh -c "cd /var/www/html/ && composer build"

    - name: Execute tests
      run: |
        docker compose exec -T --user wodby php /bin/sh -c "cd /var/www/html/ && composer test"

    - name: Cleanup
      run: |
        docker compose down
